name: Access server

on: push

jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: SSH Key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al