name: Pull Latest Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SSH
      run: sudo apt-get install openssh-client
    - name: SSH into EC2
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        ARGS: "ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} cd /var/www/html/ && git pull"
