name: Pull Latest Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SSH
      run: sudo apt-get install openssh-client
    - name: SSH into EC2
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        ARGS: "ssh ubuntu@34.222.147.193 cd /var/www/html/ && git pull"
