name: Access server

on: push

jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Creating file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo hello world > /var/www/html/hello.txt
